version: '3'
services:
  student-counselling-mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ZHlkZWhmMTI=
      - TZ=Asia/Seoul
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/schema/:/docker-entrypoint-initdb.d

volumes:
  db_data: